### ISSUE TITLE
Cancel button not works in File Dialog

### ISSUE THREAD

**Issue by UnrealKaraulov** [SamVanheer/HalfLife.UnifiedSdk.MapDecompiler#12]
Cancel button not works in File Dialog

**Comment by SamVanheer** [comment]
Are you referring to the cancel button that's part of the dialog or the cancel button on the main window? The cancel button on the main window is for cancelling ongoing decompilations, and when the file dialog is open it'll block interactions with the main window.

**Comment by UnrealKaraulov** [comment]
> Are you referring to the cancel button that's part of the dialog or the cancel button on the main window?

Directory dialog (Save path)

**Comment by UnrealKaraulov** [comment]
@SamVanheer all works, strange, possible issue in AVAST (sandbox)
