### ISSUE TITLE
de_dust2.bsp can not be compiled back after converted it to .map

### ISSUE THREAD

**Issue by UnrealKaraulov** [SamVanheer/HalfLife.UnifiedSdk.MapDecompiler#13]
de_dust2.bsp can not be compiled back after converted it to .map

Big count of errors like '**texture not found**', '**face is not planar**', 'edge is too small', etc

**Comment by SamVanheer** [comment]
Yes, that's to be expected. Decompilers for this game will never be able to produce maps that can be recompiled without changes.
