### ISSUE TITLE
Add option to apply NULL to generated faces

### ISSUE THREAD

**Issue by mfaizsyahmi** [SamVanheer/HalfLife.UnifiedSdk.MapDecompiler#23]
Tweak (or add options) to have the face-to-brush decompiler use NULL texture for the extruded faces. I think that'd be a cleaner approach, clearly marking which faces are made up by the decompiler, and the texture's visibility can be toggled off in JACK.

**Comment by SamVanheer** [comment]
Note that some generated faces will still have a texture applied. I can look into doing something about that but i don't know if it's practical to do.
