### ISSUE TITLE
mbspc produced better results than unified decompiler

### ISSUE THREAD

**Issue by TheSD** [SamVanheer/HalfLife.UnifiedSdk.MapDecompiler#28]
After decompiling a map from action half-life (ahl_astorage.bsp) using unified decompiler tree-based decompiler, I noticed some brushes were missing and some were stretched across the map. The result wasn't great. I am aware that goldsource decompiling will never be perfect due to the lack of data in goldsource maps.

I was curious so I decided to compare the updated version of mbspc from https://github.com/Garux/netradiant-custom/ and unified decompiler. I thought the results would be the same since both use tree-based decompilation methods. To my surprise, mbspc produced far better results.

Here's a comparison:

unified decompiler result:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/fa492d3c-5ce8-4487-aa9a-90a8ff0ff890)

mbspc result:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/21798b54-a552-49d7-bcf4-b6bb166ca787)

unified decompiler messing up the car and the textures on the wall:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/81ba0e65-6ae1-4ca5-80c5-a750446b2b3d)

mbspc result:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/a5602491-98fc-48a2-a76f-130f7e9f8fad)

unified decompiler result:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/4c58e90c-9867-471e-9bd2-6347ad38b0d8)

mbspc result:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/1d4f5dbe-fc68-4026-8dc5-e43a672c4f09)

unified decompiler misses a bunch of brushes in this area:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/d7c97567-9ef8-43db-ac79-689a2b67f42a)

mbspc correctly preserves the brushes:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/e2bb1aab-6d34-4550-ac0b-22446c6ed0f0)

Here both decompilers missed these brushes for some reason. I have no idea why because they are quite simple:

unified decompiler:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/e283e96b-942d-47dd-9dea-17908479ce54)

mbspc result:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/b4b9b168-badb-4f09-95c7-23e1b9f29d60)

in-game:
![scr](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/cf1a46e6-3ce5-4090-9b68-a7919c07e370)

These are my settings just in case you need them for whatever reason:
![image](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/assets/119077716/94a8c9f6-4460-4fb9-a1ef-c66d45cb33cc)

mbspc cmd options:
`mbspc -bsp2map220 ahl_astorage.bsp`

I have uploaded the map and the wad file that comes with it if you want to test it yourself.
[actionhl.zip](https://github.com/SamVanheer/HalfLife.UnifiedSdk.MapDecompiler/files/11930314/actionhl.zip)

**Comment by SamVanheer** [comment]
Thanks for reporting this. I've looked into it and i've found that this is caused by a mistake in a feature i added to correct some slightly misaligned plane normals that broke brushes in `cz_recoil`.

The mistake is that instead of rounding values to the nearest whole integer the value is always rounded *down* which produced invalid plane normals in some cases, like the plane that is supposed to cut those crate brushes. I've fixed this and the decompiler handles that map correctly now.
