### ISSUE TITLE
[Feature Request] Getting closest lightmaps values

### ISSUE THREAD

**Issue by BlackShadow** [SamVanheer/HalfLife.UnifiedSdk.MapDecompiler#29]
Is it possible to get closest lightmap values from compiled maps and creating a RAD file?

Since baked lightmap data isn't stored in BSP, I was using a manual method myself like opening compiled BSP file on BSPViewer, untextured. Using eye dropper tool in a photo editor to get closest lightmap color as RGB value then tune it a little bit to find similar value on original map

Perhaps something like this could be implemented?

**Comment by SamVanheer** [comment]
There is no way to know which textures were configured to emit light, nor is there a way to determine if lighting values were emitted by a particular texture/surface or if the values are even close to what was being used.

If you have a room with 5 different texlights then you have no way of knowing which lightmap values were affected by which texlights and how much so this is just plain guesswork which can't be automated.
