### ISSUE TITLE
Can't decompile triangle mesh ?

### ISSUE THREAD

**Issue by UnrealKaraulov** [SamVanheer/HalfLife.UnifiedSdk.MapDecompiler#30]
[gign.zip](https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/files/14150835/gign.zip)

**Comment by UnrealKaraulov** [comment]
![image](https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/assets/88730285/73f7372a-0ab8-4497-9bc7-04377f8b36f3)

**Comment by UnrealKaraulov** [comment]
![image](https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/assets/88730285/b9503336-3296-4228-9c12-ca392a5462f3)
![image](https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/assets/88730285/6df6e0a8-e8d7-4a9a-bebe-2163f3912030)

**Comment by UnrealKaraulov** [comment]
[de_dust2_with_gign.zip](https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/files/14150847/de_dust2_with_gign.zip)
Full sample (model gign.mdl added to de_dust2 via 'map->mdl to bsp(wip)' feature from newbspguy)


I got bad decompile result with latest release ( https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/releases/tag/V1.0.0.0 ) 

![image](https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/assets/88730285/97a68fa4-0426-4880-a8db-dc0de8c2a3a5)

**Comment by UnrealKaraulov** [comment]
Another map example, why Tree decompiler can't decompile this map?

![image](https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/assets/88730285/60b60e36-54db-48c9-b46e-a470be0ebfd6)
[random_lowpoly_map.zip](https://github.com/twhl-community/HalfLife.UnifiedSdk.MapDecompiler/files/14152072/random_lowpoly_map.zip)

**Comment by karakakarkarkar** [comment]
@SamVanheer face-to-brush produces an incredible amount of extra vertices. But for one face, one vertex is quite enough. Also your face-to-brush decompiler cant detect true face side. 

Possible need to invert dist for planeside with normal.



	if (face->nPlaneSide)
	{
		BSPPLANE backplane = bsp->planes[face->iPlane];
		backplane.fDist = -backplane.fDist;
		backplane.vNormal = backplane.vNormal.invert();
		return backplane;
	}
	else
	{
		return bsp->planes[face->iPlane];
	}

**Comment by UnrealKaraulov** [comment]
[@](https://discord.com/channels/291678871856742400/626030872889655296/1212263117413687347)
